"""Explicit stationary EMU motif for Phase 2A edge reconstruction.

The chemistry in this module is a deliberately synthetic test network. Its
carbon maps are declared explicitly; it is not presented as a biochemical
reaction system. Exact MIDs are never prescribed here. They are generated by
the existing COBRApy-to-mfapy bridge and :func:`run_batch_forward`.

Three alternative mapped decarboxylations feed a common two-carbon pool
``X``. A downstream mapped decarboxylation produces the one-carbon pool
``W``. The full ``X`` MID is the topology observation, while the full ``W``
MID is quarantined as a withheld prediction target.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from types import MappingProxyType
from typing import Any, Mapping, Sequence

from cobra import Metabolite, Model, Reaction
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

from .cobra_analysis import FluxSampleValidationReport, validate_flux_samples
from .cobra_to_mfapy import MfapyModelBundle, build_mfapy_model
from .configuration import (
    ExperimentConfig,
    NumericalTolerances,
    TargetFragment,
    TracerMixture,
)
from .forward import ForwardResult, run_batch_forward
from .isotope_metadata import (
    AtomMappedParticipant,
    MetaboliteIsotopeMetadata,
    ReactionIsotopeMetadata,
    collect_isotope_metadata,
    set_metabolite_metadata,
    set_reaction_metadata,
)


SUPPORT_LABELS = ("G_A", "G_B", "G_C", "G_AB", "G_AC", "G_BC")
CANDIDATE_EDGES = ("e_A", "e_B", "e_C")
SUPPORT_EDGES: Mapping[str, tuple[str, ...]] = MappingProxyType(
    {
        "G_A": ("e_A",),
        "G_B": ("e_B",),
        "G_C": ("e_C",),
        "G_AB": ("e_A", "e_B"),
        "G_AC": ("e_A", "e_C"),
        "G_BC": ("e_B", "e_C"),
    }
)

OBSERVED_TARGET_ID = "X_full"
WITHHELD_TARGET_ID = "W_full"
OBSERVED_BLOCKS = ((OBSERVED_TARGET_ID, 0, 3),)
WEIGHT_LOWER = 0.2
WEIGHT_UPPER = 0.8
DEFAULT_WEIGHT_POINT_COUNT = 11
R_MEAS = 0.005
MASTER_SEED = 20_260_809

METABOLITE_CARBONS: Mapping[str, int] = MappingProxyType(
    {"P": 3, "X": 2, "W": 1, "CO2": 1, "W_out": 1}
)
CARBON_SOURCES = frozenset(("P",))
EXCRETED_METABOLITES = frozenset(("CO2", "W_out"))

# A fixed independent-position tracer with P(labelled C1, C2, C3) equal to
# (3/4, 1/4, 1/4). Every isotopomer is strictly positive, so every generated
# observed MID component is compatible with the established Dirichlet model.
# Equal C2/C3 enrichment deliberately creates the declared full-X aliases.
TRACER_ISOTOPOMERS: Mapping[str, float] = MappingProxyType(
    {
        "#000": 0.140625,
        "#001": 0.046875,
        "#010": 0.046875,
        "#011": 0.015625,
        "#100": 0.421875,
        "#101": 0.140625,
        "#110": 0.140625,
        "#111": 0.046875,
    }
)


@dataclass(frozen=True)
class SyntheticReactionDefinition:
    """One explicit molecule-level reaction in the synthetic motif."""

    reaction_id: str
    stoichiometry: Mapping[str, float]
    included_in_isotope_model: bool
    substrates: tuple[tuple[str, str], ...] = ()
    products: tuple[tuple[str, str], ...] = ()
    fixed_flux: float | None = None


REACTION_DEFINITIONS: tuple[SyntheticReactionDefinition, ...] = (
    SyntheticReactionDefinition("SRC_P", {"P": 1.0}, False, fixed_flux=1.0),
    SyntheticReactionDefinition(
        "e_A",
        {"P": -1.0, "X": 1.0, "CO2": 1.0},
        True,
        (("P", "abc"),),
        (("X", "ab"), ("CO2", "c")),
    ),
    SyntheticReactionDefinition(
        "e_B",
        {"P": -1.0, "X": 1.0, "CO2": 1.0},
        True,
        (("P", "abc"),),
        (("X", "bc"), ("CO2", "a")),
    ),
    SyntheticReactionDefinition(
        "e_C",
        {"P": -1.0, "X": 1.0, "CO2": 1.0},
        True,
        (("P", "abc"),),
        (("X", "ca"), ("CO2", "b")),
    ),
    SyntheticReactionDefinition(
        "d_XW",
        {"X": -1.0, "W": 1.0, "CO2": 1.0},
        True,
        (("X", "ab"),),
        (("W", "a"), ("CO2", "b")),
        1.0,
    ),
    SyntheticReactionDefinition(
        "OUT_W",
        {"W": -1.0, "W_out": 1.0},
        True,
        (("W", "a"),),
        (("W_out", "a"),),
        1.0,
    ),
    SyntheticReactionDefinition(
        "DM_CO2", {"CO2": -1.0}, False, fixed_flux=2.0
    ),
    SyntheticReactionDefinition(
        "DM_W_out", {"W_out": -1.0}, False, fixed_flux=1.0
    ),
)


def _participant(metabolite_id: str, labels: str) -> AtomMappedParticipant:
    return AtomMappedParticipant(metabolite_id, tuple(labels))


def build_explicit_motif() -> Model:
    """Build the complete bounded COBRApy motif with explicit isotope maps."""

    model = Model("fluxemu_phase2a_explicit_edge_motif")
    metabolites = {
        metabolite_id: Metabolite(metabolite_id, compartment="c")
        for metabolite_id in METABOLITE_CARBONS
    }
    model.add_metabolites(metabolites.values())

    for metabolite_id, carbon_count in METABOLITE_CARBONS.items():
        set_metabolite_metadata(
            metabolites[metabolite_id],
            MetaboliteIsotopeMetadata(
                original_cobra_metabolite_id=metabolite_id,
                carbon_count=carbon_count,
                is_carbon_source=metabolite_id in CARBON_SOURCES,
                is_excreted=metabolite_id in EXCRETED_METABOLITES,
                symmetry=False,
                include_in_isotope_model=True,
            ),
        )

    for definition in REACTION_DEFINITIONS:
        lower_bound = 0.0 if definition.fixed_flux is None else definition.fixed_flux
        upper_bound = 1.0 if definition.fixed_flux is None else definition.fixed_flux
        reaction = Reaction(
            definition.reaction_id,
            name=f"synthetic Phase 2A {definition.reaction_id}",
            lower_bound=lower_bound,
            upper_bound=upper_bound,
        )
        reaction.add_metabolites(
            {
                metabolites[metabolite_id]: coefficient
                for metabolite_id, coefficient in definition.stoichiometry.items()
            }
        )
        set_reaction_metadata(
            reaction,
            ReactionIsotopeMetadata(
                original_cobra_reaction_id=definition.reaction_id,
                directional_id=f"synthetic:{definition.reaction_id}:forward",
                direction="forward",
                include_in_isotope_model=definition.included_in_isotope_model,
                substrates=tuple(
                    _participant(metabolite_id, labels)
                    for metabolite_id, labels in definition.substrates
                ),
                products=tuple(
                    _participant(metabolite_id, labels)
                    for metabolite_id, labels in definition.products
                ),
            ),
        )
        model.add_reactions([reaction])

    model.objective = model.reactions.OUT_W
    model.objective_direction = "max"
    model.notes["FLUXEMU_PHASE2A_CHEMISTRY"] = (
        "Synthetic atom-mapped test chemistry; not a known biochemical network."
    )
    return model


def build_experiment() -> ExperimentConfig:
    """Return the fixed stationary tracer and observed/withheld targets."""

    return ExperimentConfig(
        tracers=(
            TracerMixture(
                metabolite_id="P",
                isotopomer_fractions=dict(TRACER_ISOTOPOMERS),
                correction="no",
            ),
        ),
        targets=(
            TargetFragment(
                fragment_id=OBSERVED_TARGET_ID,
                metabolite_id="X",
                atom_positions=(1, 2),
                analytical_method="intermediate",
                formula="C2H4O2",
                correction="no",
            ),
            TargetFragment(
                fragment_id=WITHHELD_TARGET_ID,
                metabolite_id="W",
                atom_positions=(1,),
                analytical_method="intermediate",
                formula="CH2O",
                correction="no",
            ),
        ),
        fraction_of_optimum=1.0,
        sample_count=1,
        sampler="achr",
        seed=MASTER_SEED,
        tolerances=NumericalTolerances(),
    )


def support_edges(support_label: str) -> tuple[str, ...]:
    """Return the declared positive-flux candidate edges for one support."""

    try:
        return SUPPORT_EDGES[str(support_label)]
    except KeyError as error:
        raise ValueError(f"unknown support label {support_label!r}") from error


def mixing_weight_grid(
    point_count: int = DEFAULT_WEIGHT_POINT_COUNT,
) -> np.ndarray:
    """Return the frozen bounded two-edge coordinate, including ``w=0.5``."""

    count = int(point_count)
    if count < 3 or count % 2 == 0:
        raise ValueError("the two-edge weight grid must be odd and at least three")
    values = np.linspace(WEIGHT_LOWER, WEIGHT_UPPER, count, dtype=float)
    values.setflags(write=False)
    return values


def _state_member_ids(count: int, offset: int = 0) -> tuple[str, ...]:
    return tuple(f"emu_member_{offset + index:06d}" for index in range(int(count)))


@dataclass(frozen=True)
class SupportFluxStates:
    """Complete feasible flux vectors plus quarantined construction metadata."""

    support_label: str
    active_edges: tuple[str, ...]
    member_ids: tuple[str, ...]
    mixing_weights: np.ndarray | None
    fluxes: pd.DataFrame
    validation: FluxSampleValidationReport


def construct_support_flux_states(
    model: Model,
    support_label: str,
    mixing_weights: Sequence[float] | np.ndarray | None = None,
    *,
    member_id_offset: int = 0,
    tolerances: NumericalTolerances | None = None,
) -> SupportFluxStates:
    """Construct complete COBRApy states for one declared active support."""

    active_edges = support_edges(support_label)
    if len(active_edges) == 1:
        if mixing_weights is not None:
            raise ValueError("single-edge supports do not have a mixing weight")
        weights: np.ndarray | None = None
        row_weights = np.asarray([1.0], dtype=float)
    else:
        if mixing_weights is None:
            raise ValueError("two-edge supports require mixing weights")
        row_weights = np.asarray(mixing_weights, dtype=float)
        if row_weights.ndim != 1 or len(row_weights) < 1:
            raise ValueError("mixing weights must be a nonempty vector")
        if (
            not np.all(np.isfinite(row_weights))
            or np.any(row_weights < WEIGHT_LOWER)
            or np.any(row_weights > WEIGHT_UPPER)
        ):
            raise ValueError("mixing weights must lie in [0.2, 0.8]")
        weights = np.array(row_weights, copy=True)
        weights.setflags(write=False)

    reaction_ids = [reaction.id for reaction in model.reactions]
    member_ids = _state_member_ids(len(row_weights), offset=member_id_offset)
    rows: list[dict[str, float]] = []
    for weight in row_weights:
        flux = {reaction_id: 0.0 for reaction_id in reaction_ids}
        flux["SRC_P"] = 1.0
        if len(active_edges) == 1:
            edge_fluxes = (1.0,)
        else:
            complement = float(
                np.clip(1.0 - float(weight), WEIGHT_LOWER, WEIGHT_UPPER)
            )
            edge_fluxes = (float(weight), complement)
        for edge, value in zip(active_edges, edge_fluxes, strict=True):
            flux[edge] = value
        flux["d_XW"] = 1.0
        flux["OUT_W"] = 1.0
        flux["DM_CO2"] = 2.0
        flux["DM_W_out"] = 1.0
        rows.append(flux)

    frame = pd.DataFrame(rows, index=pd.Index(member_ids, name="sample_id"))
    frame = frame.loc[:, reaction_ids]
    validation = validate_flux_samples(
        model,
        frame,
        objective_floor=1.0,
        tolerances=NumericalTolerances() if tolerances is None else tolerances,
    )
    if not validation.valid:
        raise ValueError(
            f"constructed {support_label} flux states are infeasible: "
            + "; ".join(validation.errors)
        )
    return SupportFluxStates(
        support_label=str(support_label),
        active_edges=active_edges,
        member_ids=member_ids,
        mixing_weights=weights,
        fluxes=frame,
        validation=validation,
    )


def construct_representative_states(model: Model) -> tuple[SupportFluxStates, ...]:
    """Construct one feasible midpoint state for every support."""

    result: list[SupportFluxStates] = []
    offset = 0
    for support_label in SUPPORT_LABELS:
        weights = None if len(support_edges(support_label)) == 1 else (0.5,)
        state = construct_support_flux_states(
            model,
            support_label,
            weights,
            member_id_offset=offset,
        )
        result.append(state)
        offset += len(state.member_ids)
    return tuple(result)


def combine_flux_states(states: Sequence[SupportFluxStates]) -> pd.DataFrame:
    """Combine separately audited complete state frames without changing order."""

    items = tuple(states)
    if not items:
        raise ValueError("at least one support state collection is required")
    columns = tuple(items[0].fluxes.columns)
    if any(tuple(item.fluxes.columns) != columns for item in items[1:]):
        raise ValueError("support state collections use incompatible reaction orders")
    result = pd.concat([item.fluxes for item in items], axis=0)
    if result.index.has_duplicates:
        raise ValueError("combined support member identifiers must be globally unique")
    return result


@dataclass(frozen=True)
class ForwardSystem:
    """The one in-memory model/bundle pair used by stationary forward runs."""

    cobra_model: Model
    experiment: ExperimentConfig
    mfapy_bundle: MfapyModelBundle


def build_forward_system() -> ForwardSystem:
    """Build the existing in-memory FluxEMU stationary forward path."""

    model = build_explicit_motif()
    experiment = build_experiment()
    bundle = build_mfapy_model(model, collect_isotope_metadata(model), experiment)
    return ForwardSystem(model, experiment, bundle)


def run_forward_states(
    system: ForwardSystem, states: Sequence[SupportFluxStates]
) -> ForwardResult:
    """Run complete feasible states through FluxEMU's stationary EMU engine."""

    frame = combine_flux_states(states)
    validation = validate_flux_samples(
        system.cobra_model,
        frame,
        objective_floor=1.0,
        tolerances=system.experiment.tolerances,
    )
    if not validation.valid:
        raise ValueError("combined forward-state batch is not COBRA-feasible")
    return run_batch_forward(system.mfapy_bundle, frame, system.experiment)


def _readonly_float_array(values: Sequence[float] | np.ndarray) -> np.ndarray:
    result = np.array(values, dtype=float, copy=True)
    result.setflags(write=False)
    return result


def _validate_mid_rows(
    values: np.ndarray,
    *,
    component_count: int,
    context: str,
    require_positive: bool,
) -> None:
    rows = np.asarray(values, dtype=float)
    if rows.ndim != 2 or rows.shape[1] != int(component_count) or len(rows) < 1:
        raise ValueError(f"{context} has an invalid MID shape")
    if not np.all(np.isfinite(rows)):
        raise ValueError(f"{context} contains a non-finite MID component")
    if require_positive and np.any(rows <= 0.0):
        raise ValueError(f"{context} MID components must be strictly positive")
    if not require_positive and np.any(rows < 0.0):
        raise ValueError(f"{context} contains a negative MID component")
    if not np.allclose(np.sum(rows, axis=1), 1.0, rtol=0.0, atol=1.0e-12):
        raise ValueError(f"{context} MIDs must sum to one")


@dataclass(frozen=True)
class ObservableMIDClass:
    """The complete and deliberately narrow input to the testing engine."""

    member_ids: tuple[str, ...]
    blocks: tuple[tuple[str, int, int], ...]
    exact_mids: np.ndarray

    def __post_init__(self) -> None:
        member_ids = tuple(str(value) for value in self.member_ids)
        blocks = tuple(
            (str(name), int(start), int(stop)) for name, start, stop in self.blocks
        )
        exact_mids = _readonly_float_array(self.exact_mids)
        if not member_ids or len(set(member_ids)) != len(member_ids):
            raise ValueError("observable member identifiers must be unique")
        if blocks != OBSERVED_BLOCKS:
            raise ValueError("the topology observation must contain only X_full")
        if exact_mids.shape[0] != len(member_ids):
            raise ValueError("observable MID rows and member identifiers do not align")
        _validate_mid_rows(
            exact_mids,
            component_count=3,
            context="observed X",
            require_positive=True,
        )
        object.__setattr__(self, "member_ids", member_ids)
        object.__setattr__(self, "blocks", blocks)
        object.__setattr__(self, "exact_mids", exact_mids)

    @property
    def member_count(self) -> int:
        return len(self.member_ids)


@dataclass(frozen=True)
class SupportClassMetadata:
    """Construction-only fields that must never enter a topology decision."""

    support_label: str
    active_edges: tuple[str, ...]
    member_ids: tuple[str, ...]
    mixing_weights: np.ndarray | None
    complete_fluxes: pd.DataFrame
    withheld_mids: np.ndarray

    def __post_init__(self) -> None:
        support_label = str(self.support_label)
        active_edges = tuple(str(value) for value in self.active_edges)
        member_ids = tuple(str(value) for value in self.member_ids)
        if support_edges(support_label) != active_edges:
            raise ValueError("construction metadata has an invalid active support")
        if tuple(self.complete_fluxes.index) != member_ids:
            raise ValueError("construction fluxes and member identifiers do not align")
        withheld = _readonly_float_array(self.withheld_mids)
        if withheld.shape[0] != len(member_ids):
            raise ValueError("withheld MIDs and member identifiers do not align")
        _validate_mid_rows(
            withheld,
            component_count=2,
            context="withheld W",
            require_positive=True,
        )
        if len(active_edges) == 1:
            if self.mixing_weights is not None:
                raise ValueError("single-edge metadata cannot contain mixing weights")
            weights = None
        else:
            if self.mixing_weights is None:
                raise ValueError("two-edge metadata requires mixing weights")
            weights = _readonly_float_array(self.mixing_weights)
            if weights.shape != (len(member_ids),):
                raise ValueError("mixing weights and member identifiers do not align")
        object.__setattr__(self, "support_label", support_label)
        object.__setattr__(self, "active_edges", active_edges)
        object.__setattr__(self, "member_ids", member_ids)
        object.__setattr__(self, "mixing_weights", weights)
        object.__setattr__(self, "complete_fluxes", self.complete_fluxes.copy())
        object.__setattr__(self, "withheld_mids", withheld)


@dataclass(frozen=True)
class ForwardGeneratedClasses:
    """Six observable-only classes and their separately held state metadata."""

    observables: tuple[ObservableMIDClass, ...]
    metadata: tuple[SupportClassMetadata, ...]
    forward_validation: Mapping[str, Any]
    weight_point_count: int

    def __post_init__(self) -> None:
        observables = tuple(self.observables)
        metadata = tuple(self.metadata)
        if len(observables) != len(SUPPORT_LABELS) or len(metadata) != len(
            SUPPORT_LABELS
        ):
            raise ValueError("all six support classes are required")
        if tuple(item.support_label for item in metadata) != SUPPORT_LABELS:
            raise ValueError("support metadata must use the declared class order")
        for observable, hidden in zip(observables, metadata, strict=True):
            if observable.member_ids != hidden.member_ids:
                raise ValueError("observable and hidden member identifiers do not align")
        if not bool(self.forward_validation.get("valid", False)):
            raise ValueError("forward generation did not pass MID validation")
        object.__setattr__(self, "observables", observables)
        object.__setattr__(self, "metadata", metadata)
        object.__setattr__(
            self, "forward_validation", MappingProxyType(dict(self.forward_validation))
        )
        object.__setattr__(self, "weight_point_count", int(self.weight_point_count))

    @property
    def support_labels(self) -> tuple[str, ...]:
        return tuple(item.support_label for item in self.metadata)


def generate_forward_classes(
    *,
    weight_point_count: int = DEFAULT_WEIGHT_POINT_COUNT,
    system: ForwardSystem | None = None,
) -> ForwardGeneratedClasses:
    """Generate all class signatures with the stationary FluxEMU EMU path."""

    count = int(weight_point_count)
    weights = mixing_weight_grid(count)
    forward_system = build_forward_system() if system is None else system
    states: list[SupportFluxStates] = []
    offset = 0
    for support_label in SUPPORT_LABELS:
        class_weights = (
            None if len(support_edges(support_label)) == 1 else weights
        )
        item = construct_support_flux_states(
            forward_system.cobra_model,
            support_label,
            class_weights,
            member_id_offset=offset,
            tolerances=forward_system.experiment.tolerances,
        )
        states.append(item)
        offset += len(item.member_ids)

    forward = run_forward_states(forward_system, states)
    observables: list[ObservableMIDClass] = []
    metadata: list[SupportClassMetadata] = []
    for state in states:
        observed = np.asarray(
            [
                forward.predictions[member_id][OBSERVED_TARGET_ID]
                for member_id in state.member_ids
            ],
            dtype=float,
        )
        withheld = np.asarray(
            [
                forward.predictions[member_id][WITHHELD_TARGET_ID]
                for member_id in state.member_ids
            ],
            dtype=float,
        )
        observables.append(
            ObservableMIDClass(
                member_ids=state.member_ids,
                blocks=OBSERVED_BLOCKS,
                exact_mids=observed,
            )
        )
        metadata.append(
            SupportClassMetadata(
                support_label=state.support_label,
                active_edges=state.active_edges,
                member_ids=state.member_ids,
                mixing_weights=state.mixing_weights,
                complete_fluxes=state.fluxes,
                withheld_mids=withheld,
            )
        )
    return ForwardGeneratedClasses(
        observables=tuple(observables),
        metadata=tuple(metadata),
        forward_validation=forward.validation,
        weight_point_count=count,
    )


@dataclass(frozen=True)
class ForwardAliasDiagnostic:
    """Numerical verification of one declared construction-level identity."""

    left_support: str
    right_support: str
    relation: str
    comparison_count: int
    maximum_absolute_component_error: float
    tolerance: float
    passed: bool


def _alias_diagnostic(
    left_support: str,
    right_support: str,
    relation: str,
    left_mids: np.ndarray,
    right_mids: np.ndarray,
    tolerance: float,
) -> ForwardAliasDiagnostic:
    left = np.asarray(left_mids, dtype=float)
    right = np.asarray(right_mids, dtype=float)
    if left.shape != right.shape or left.ndim != 2:
        raise ValueError("alias-verification MID arrays must align")
    maximum = float(np.max(np.abs(left - right)))
    return ForwardAliasDiagnostic(
        left_support=str(left_support),
        right_support=str(right_support),
        relation=str(relation),
        comparison_count=len(left),
        maximum_absolute_component_error=maximum,
        tolerance=float(tolerance),
        passed=maximum <= float(tolerance),
    )


def verify_declared_forward_aliases(
    classes: ForwardGeneratedClasses,
    *,
    tolerance: float = 1.0e-12,
) -> tuple[ForwardAliasDiagnostic, ...]:
    """Verify the intended full-X aliases on EMU-generated class rows."""

    by_label = dict(zip(SUPPORT_LABELS, classes.observables, strict=True))
    g_a = by_label["G_A"].exact_mids
    g_c = by_label["G_C"].exact_mids
    g_ac = by_label["G_AC"].exact_mids
    diagnostics = (
        _alias_diagnostic(
            "G_A",
            "G_C",
            "single-edge maps retain equal-enrichment carbon pairs",
            g_a,
            g_c,
            tolerance,
        ),
        _alias_diagnostic(
            "G_A",
            "G_AC",
            "every bounded A/C mixture has the common full-X MID",
            np.repeat(g_a, len(g_ac), axis=0),
            g_ac,
            tolerance,
        ),
        _alias_diagnostic(
            "G_C",
            "G_AC",
            "every bounded A/C mixture has the common full-X MID",
            np.repeat(g_c, len(g_ac), axis=0),
            g_ac,
            tolerance,
        ),
        _alias_diagnostic(
            "G_AB",
            "G_BC",
            "mirrored coordinates w_BC=1-w_AB give the same full-X MID",
            by_label["G_AB"].exact_mids,
            by_label["G_BC"].exact_mids[::-1],
            tolerance,
        ),
    )
    if not all(item.passed for item in diagnostics):
        worst = max(
            diagnostics, key=lambda item: item.maximum_absolute_component_error
        )
        raise ValueError(
            "declared forward alias failed for "
            f"{worst.left_support}/{worst.right_support}: "
            f"{worst.maximum_absolute_component_error:.12g}"
        )
    return diagnostics


@dataclass(frozen=True)
class PairwiseObservableGeometry:
    """Deterministic represented-grid distance for two observable classes."""

    left_support: str
    right_support: str
    minimum_l2: float
    minimum_rms: float
    closest_left_member_id: str
    closest_right_member_id: str
    intersects_at_tolerance: bool
    set_equal_at_tolerance: bool


def pairwise_observable_geometry(
    classes: ForwardGeneratedClasses,
    *,
    tolerance: float = 1.0e-12,
) -> tuple[PairwiseObservableGeometry, ...]:
    """Return all 15 observed-X grid comparisons without hidden coordinates."""

    result: list[PairwiseObservableGeometry] = []
    for left_index in range(len(SUPPORT_LABELS)):
        for right_index in range(left_index + 1, len(SUPPORT_LABELS)):
            left = classes.observables[left_index]
            right = classes.observables[right_index]
            right_tree = cKDTree(right.exact_mids)
            left_tree = cKDTree(left.exact_mids)
            left_distances, left_neighbours = right_tree.query(left.exact_mids, k=1)
            right_distances, _ = left_tree.query(right.exact_mids, k=1)
            nearest_left = int(np.argmin(left_distances))
            nearest_right = int(left_neighbours[nearest_left])
            minimum = float(left_distances[nearest_left])
            result.append(
                PairwiseObservableGeometry(
                    left_support=SUPPORT_LABELS[left_index],
                    right_support=SUPPORT_LABELS[right_index],
                    minimum_l2=minimum,
                    minimum_rms=minimum / math.sqrt(3.0),
                    closest_left_member_id=left.member_ids[nearest_left],
                    closest_right_member_id=right.member_ids[nearest_right],
                    intersects_at_tolerance=minimum <= float(tolerance),
                    set_equal_at_tolerance=bool(
                        float(np.max(left_distances)) <= float(tolerance)
                        and float(np.max(right_distances)) <= float(tolerance)
                    ),
                )
            )
    return tuple(result)


__all__ = [
    "CANDIDATE_EDGES",
    "CARBON_SOURCES",
    "DEFAULT_WEIGHT_POINT_COUNT",
    "EXCRETED_METABOLITES",
    "ForwardAliasDiagnostic",
    "ForwardGeneratedClasses",
    "ForwardSystem",
    "MASTER_SEED",
    "METABOLITE_CARBONS",
    "OBSERVED_BLOCKS",
    "OBSERVED_TARGET_ID",
    "ObservableMIDClass",
    "PairwiseObservableGeometry",
    "R_MEAS",
    "REACTION_DEFINITIONS",
    "SUPPORT_EDGES",
    "SUPPORT_LABELS",
    "SupportFluxStates",
    "SupportClassMetadata",
    "SyntheticReactionDefinition",
    "TRACER_ISOTOPOMERS",
    "WEIGHT_LOWER",
    "WEIGHT_UPPER",
    "WITHHELD_TARGET_ID",
    "build_experiment",
    "build_explicit_motif",
    "build_forward_system",
    "combine_flux_states",
    "construct_representative_states",
    "construct_support_flux_states",
    "generate_forward_classes",
    "mixing_weight_grid",
    "pairwise_observable_geometry",
    "run_forward_states",
    "support_edges",
    "verify_declared_forward_aliases",
]
